### ISSUE TITLE
Support import assertions

### ISSUE THREAD

**Issue by bluwy** [bluwy/vite-plugin-iso-import#4]
```js
import { foo } from './client-module' assert { only: 'client' }
import { bar } from './server-module' assert { only: 'server' }
```

**Comment by bluwy** [comment]
Recently found that import assertions shouldn't change it's evaluation, so this syntax likely isn't semantic. [import reflection](https://github.com/bluwy/vite-plugin-iso-import) may work, but it's only stage 1. Until then we may have to shelf this idea.

**Comment by wobsoriano** [comment]
is it possible to use `.{client|server}.{ts|js}` instead of `?{server|client}`? Or would that be a rewrite?

Playing around with a Nuxt 3 app and want to have a data loader/action like what Remix does.

```vue
<script setup lang="ts">
import { useServerData } from '@/lib/loader'
import { prisma } from '@/lib/prisma?server'

const todos = await useServerData(() => {
  return prisma.todo.findMany()
})
</script>


<template>
  <div>
    <ul v-if="todos">
      <li v-for="t in todos" :key="t.id">{{ t.title }}</li>
    </ul>
    <div v-else>No todos</div>
  </div>
</template>
```

Was able to implement a basic loader https://github.com/wobsoriano/nuxt-data-playground

**Comment by bluwy** [comment]
It's likely not a lot of work to support that, but that would only work for files since you can't use that for importing packages. It could also conflict if you actually want to load a file with the `.client` or `.server` name, so it would need some fs checks for each import.
